server:
  port: 9082
nacos:
  host: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos
dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
rpc:
  service:
    version: 1.0.1
spring:
  application:
    name: gang-mars-user