server:
  port: 9080
nacos:
  server-address: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
rpc:
  service:
    version: 1.0.1
spring:
  application:
    name: gang-mars-order-provider